sudo: false
language: python
env:
  - PYTHON_VERSION=3.5
before_install:
  - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
  - chmod +x miniconda.sh
  - ./miniconda.sh -b
  - export PATH=/home/travis/miniconda3/bin:$PATH
install:
  - conda create --yes -c biocore -n test-env python=$PYTHON_VERSION pytest pytest-cov scikit-bio
  - conda install --yes -c biocore fasttree
  - source activate test-env
  - pip install https://github.com/qiime2/qiime2/archive/master.zip https://github.com/qiime2/q2-types/archive/master.zip
  - pip install flake8 coveralls
  - pip install .
  - git clone https://github.com/qiime2/q2lint
script:
  - py.test --cov=q2_phylogeny
  - flake8
  - python q2lint/q2lint.py
after_success:
  - coveralls
