{% set data = load_setup_py_data() %}
{% set version = data.get('version') or 'placehold' %}
{% set release = '.'.join(version.split('.')[:2]) %}

package:
  name: q2-phylogeny
  version: {{ version }}

source:
  path: ../..

build:
  script: make install

requirements:
  host:
    - python {{ python }}
    - setuptools

  run:
    - python {{ python }}
    - scikit-bio
    - qiime2 {{ release }}.*
    - q2-types {{ release }}.*
    - q2-alignment {{ release }}.*
    - fasttree >=2.1.10
    - raxml
    - iqtree >=1.6.4

test:
  imports:
    - q2_phylogeny
    - qiime2.plugins.phylogeny

about:
  home: https://qiime2.org
  license: BSD-3-Clause
  license_family: BSD
