{% set data = load_setup_py_data() %}
{% set version = data.get('version') or 'placehold' %}

package:
  name: q2-phylogeny
  version: {{ version }}

source:
  path: ../..

build:
  script: make install

requirements:
  host:
    - python {{ python }}
    - setuptools

  run:
    - python {{ python }}
    - scikit-bio {{ scikit_bio }}
    - qiime2 {{ qiime2_epoch }}.*
    - q2-types {{ qiime2_epoch }}.*
    - q2-alignment {{ qiime2_epoch }}.*
    # fasttree pinned because newer versions don't include fasttreemp on osx:
    # https://github.com/bioconda/bioconda-recipes/blob/master/recipes/fasttree/build.sh
    - fasttree ==2.1.10=0
    - raxml
    - iqtree >=1.6.4
    - pytest

test:
  requires:
    - qiime2 >={{ qiime2 }}
    - q2-types >={{ q2_types }}
    - q2-alignment >={{ q2_alignment }}
    - pytest

  imports:
    - q2_phylogeny
    - qiime2.plugins.phylogeny

about:
  home: https://qiime2.org
  license: BSD-3-Clause
  license_family: BSD
